import { useState, useEffect } from "react";
import { useNavigate, useLocation } from "react-router-dom";
import { Menu, X, Phone, User, Shield } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";

const navItems = [
  { label: "О нас", href: "#about" }, { label: "Автопарк", href: "#fleet" }, { label: "Сравнение", href: "#compare" }, { label: "Условия", href: "#terms" }, { label: "Преимущества", href: "#why-us" }, { label: "Отзывы", href: "#reviews" }, { label: "Удобства", href: "#features" }, { label: "Туристам", href: "#tourism" }, { label: "Моё бронирование", href: "/my-booking" }, { label: "Контакты", href: "#contact" },
];
const Brand = () => <span className="inline-flex items-center gap-2 text-lg font-black tracking-[0.18em] text-foreground"><span className="w-8 h-8 rounded border border-slate-400/50 bg-gradient-to-br from-slate-100 via-slate-400 to-slate-700 text-slate-950 flex items-center justify-center text-xs tracking-normal">3D</span>DRIVE</span>;

const Navbar = () => {
  const [isOpen, setIsOpen] = useState(false); const [scrolled, setScrolled] = useState(false); const [isLoggedIn, setIsLoggedIn] = useState(false); const [isAdmin, setIsAdmin] = useState(false); const navigate = useNavigate(); const location = useLocation();
  useEffect(() => { const checkAdmin = async (userId: string | undefined) => { if (!userId) { setIsAdmin(false); return; } const { data } = await supabase.from("user_roles").select("role").eq("user_id", userId).eq("role", "admin").maybeSingle(); setIsAdmin(!!data); }; supabase.auth.getSession().then(({ data: { session } }) => { setIsLoggedIn(!!session); checkAdmin(session?.user?.id); }); const { data: { subscription } } = supabase.auth.onAuthStateChange((_event, session) => { setIsLoggedIn(!!session); checkAdmin(session?.user?.id); }); return () => subscription.unsubscribe(); }, []);
  useEffect(() => { const handleScroll = () => setScrolled(window.scrollY > 50); window.addEventListener("scroll", handleScroll); return () => window.removeEventListener("scroll", handleScroll); }, []);
  const handleNavClick = (e: React.MouseEvent<HTMLAnchorElement>, href: string) => { e.preventDefault(); setIsOpen(false); if (href.startsWith("#")) { if (location.pathname !== "/") { navigate("/"); setTimeout(() => document.querySelector(href)?.scrollIntoView({ behavior: "smooth" }), 300); } else document.querySelector(href)?.scrollIntoView({ behavior: "smooth" }); } else navigate(href); };
  return <nav className={`fixed top-0 left-0 right-0 z-50 transition-all duration-500 ${scrolled ? "bg-background/95 backdrop-blur-md border-b border-border" : "bg-transparent"}`}><div className="container mx-auto px-4 flex items-center justify-between h-20"><a href="/" onClick={(e) => { e.preventDefault(); navigate("/"); window.scrollTo({ top: 0, behavior: "smooth" }); }}><Brand /></a><div className="hidden lg:flex items-center gap-8">{navItems.map((item) => <a key={item.href} href={item.href} onClick={(e) => handleNavClick(e, item.href)} className="text-sm font-medium text-muted-foreground hover:text-primary transition-colors">{item.label}</a>)}<a href={isLoggedIn ? "/profile" : "/auth"} onClick={(e) => handleNavClick(e, isLoggedIn ? "/profile" : "/auth")} className="flex items-center gap-2 bg-secondary text-foreground px-4 py-2.5 rounded-lg text-sm font-medium"><User className="w-4 h-4" />{isLoggedIn ? "Кабинет" : "Войти"}</a>{isAdmin && <a href="/admin" onClick={(e) => handleNavClick(e, "/admin")} className="flex items-center gap-2 bg-primary/15 text-primary px-4 py-2.5 rounded-lg text-sm font-semibold"><Shield className="w-4 h-4" />Админ</a>}<a href="tel:+79868262332" className="flex items-center gap-2 bg-gradient-gold text-primary-foreground px-5 py-2.5 rounded-lg text-sm font-semibold"><Phone className="w-4 h-4" />Позвонить</a></div><button onClick={() => setIsOpen(!isOpen)} className="lg:hidden text-foreground">{isOpen ? <X className="w-6 h-6" /> : <Menu className="w-6 h-6" />}</button></div>{isOpen && <div className="lg:hidden bg-background/98 backdrop-blur-md border-b border-border"><div className="container mx-auto px-4 py-6 flex flex-col gap-4">{navItems.map((item) => <a key={item.href} href={item.href} onClick={(e) => handleNavClick(e, item.href)} className="text-base font-medium text-muted-foreground hover:text-primary py-2">{item.label}</a>)}<a href={isLoggedIn ? "/profile" : "/auth"} onClick={(e) => handleNavClick(e, isLoggedIn ? "/profile" : "/auth")} className="flex items-center justify-center gap-2 bg-secondary text-foreground px-5 py-3 rounded-lg text-sm font-medium"><User className="w-4 h-4" />{isLoggedIn ? "Личный кабинет" : "Войти / Регистрация"}</a>{isAdmin && <a href="/admin" onClick={(e) => handleNavClick(e, "/admin")} className="flex items-center justify-center gap-2 bg-primary/15 text-primary px-5 py-3 rounded-lg text-sm font-semibold"><Shield className="w-4 h-4" />Админ-панель</a>}<a href="tel:+79868262332" className="flex items-center justify-center gap-2 bg-gradient-gold text-primary-foreground px-5 py-3 rounded-lg text-sm font-semibold"><Phone className="w-4 h-4" />+7 (986) 826 23 32</a></div></div>}</nav>;
};
export default Navbar;
